/**
 *  (c) 2007 S Luz <luzs@acm.org>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
*/
package modnlp.tc.util;

import modnlp.tc.tsr.*;
import modnlp.tc.parser.*;
import modnlp.tc.dstruct.*;

import modnlp.dstruct.*;

import java.io.*;
import java.util.Enumeration;
import java.util.Arrays;

/**
 *  Make term co-occurrence matrix and export it to a file
 *
 * @author  S Luz &#60;luzs@acm.org&#62;
 * @version <font size=-1>$Id: $</font>
 * @see  
*/

public class MakeCoOccur {

  private  CorpusList clist = null;
  private  StopWordList swlist = null;
  private  int aggressiveness =0;
  /** 
   *  Set up the main user interface items
   */
  public  MakeCoOccur(String clist, String swlist, String aggr) {
    super();
    this.clist = new CorpusList(clist);
    this.swlist = new StopWordList(swlist);
    this.aggressiveness = (new Integer(aggr)).intValue();
    return;
  }

  /** 
   * parseNews: Set up parser object, perform parsing, and print
   *     indented contents onto stdout (for test purposes only)
   */
  public ParsedCorpus parse(String filename, String plugin) throws Exception
  {
    Parser np = IOUtil.loadParserPlugin(plugin);
    np.setFilename(filename);
    return np.getParsedCorpus();
  }


   private void computeScores (TermFilter tf, String methodOrCat) {
    if ( methodOrCat.equals("_MAX") )
      tf.computeGlobalScoresMAX();
    else if ( methodOrCat.equals("_WAVG") )
      tf.computeGlobalScoresWAVG();
    else if ( methodOrCat.equals("_SUM") )
      tf.computeGlobalScoresSUM();
    else if ( methodOrCat.equals("_DFG") )
      ((DocumentFrequency)tf).computeGlobalDocFrequency();
    else
      tf.computeLocalScores(methodOrCat);
  }


  public WordFrequencyPair[] filter(String method, TCProbabilityModel pm, String categ) 
  throws Exception{
    System.err.println("Starting filtering...");
    WordFrequencyPair[] wsp;
    if (method.equals("dfg")) {
      System.err.println("Filtering term set by document frequency (global)");
      DocumentFrequency tf = new DocumentFrequency();
      tf.initialise(pm);
      computeScores(tf, categ);
      wsp = tf.getReducedFreqList(aggressiveness);
    }
    else {
      System.err.println("Reducing term set by "+method);    
      TermFilter tf = IOUtil.loadTSRPlugin(method);
      tf.initialise(pm);
      computeScores(tf, categ);
      wsp = tf.getReducedFreqList(aggressiveness);
    }
    return wsp;
  }

  public static void main(String[] args) {
    try {
      MakeCoOccur f = new MakeCoOccur(args[0],args[1],args[2]);
      String termFilter = args[3];
      String category = args[4];
      String docRepresentation = args[5];
      String parser = args.length > 6 ? args[6] : "NewsParser";
      BVProbabilityModel pm = new BVProbabilityModel();
      for (Enumeration e = f.clist.elements(); e.hasMoreElements() ;)
        {
          String fname = (String)e.nextElement();
          System.err.print("\n----- Processing: "+fname+" ------\n");
          pm.addParsedCorpus(f.parse(fname,parser), f.swlist);
        }
      System.gc();
      WordFrequencyPair[] rts = f.filter(termFilter, pm, category);
      // pm.trimTermSet(rts);
      System.err.println("Creating co-occurrence file");
      if (category.charAt(0) == '_')
        category = null;
      if (docRepresentation.equalsIgnoreCase("arff")){
        // print header line (arff comment)
        System.out.println("% File generated by \n%  modnlp.tc.util.MakeCoOccur "+
                           args[0]+" "+args[1]+" "+args[2]+
                           " "+args[3]+" "+args[4]+" "+args[5]+"\n%\n"+
                           "% Date: "+(new java.util.Date())+"\n");
        ARFFUtil.printTermCoOccurARFF(pm, rts, System.out);
      }
      else if (docRepresentation.equalsIgnoreCase("csv"))
        ARFFUtil.printTermCoOccurCSV(pm, rts, System.out);
      else
        System.err.print("\nInvalid representation scheme: "+docRepresentation);
    }
    catch (Exception e){
      System.err.println("\nUsage: MakeCoOccur CORPUS_LIST STOPWDLIST AGGRESSIVENESS TF_METHOD CATEG REPR");
      System.err.println("       tokenise each file in CORPUS_LIST, remove words in STOPWDLIST");
      System.err.println("       and reduce the term set by a factor of AGGRESSIVENESS.\n");
      System.err.println(" TF_METHOD: term filtering method. One of: 'df' (document frequency, local),");
      System.err.println("            'dfg' (document frequency, global),");
      System.err.println("            'ig' (information gain)");
      System.err.println("            'gss' (GSS coefficient)");
      System.err.println("            'or' (Odds ratio)");
      System.err.println(" CATEG: taget category (e.g. 'acq'. Last attribute of an instance) or");
      System.err.println("    a method for combining local scores. One of:");
      System.err.println("            '_DFG' (global document frequency),");
      System.err.println("            '_MAX' (maximum local score),");
      System.err.println("            '_SUM' (sum of local scores),");
      System.err.println("            '_WAVG' (sum of local scores wbeighted by category generality),");
      System.err.println(" REPR: document representation (one of {arff, csv}\n");
      System.err.println(" PARSER: parser to be used [default: 'NewsParser']");
      System.err.println("  'LingspamEmailParser': Androutsopoulos' lingspam corpus,");
      System.err.println("  'NewsParser':  REUTERS-21578 corpus, XML version.");
      //e.printStackTrace();
    } 
  }
}
