(jde-project-file-version "1.0")
(jde-set-variables
 '(jde-global-classpath (quote ("../../../lib/MinML2.jar" "../..")))
 '(jde-run-working-directory "../..")
 '(jde-run-read-app-args t)
 '(jde-compile-option-debug (quote ("all" (t nil nil))))
 '(jde-run-read-app-args t)
 '(jde-db-read-app-args t)
 '(jde-run-option-vm-args (quote ("-Dfile.encoding=UTF8")))
 '(jde-sourcepath (quote ("../..")))
 '(jde-compile-option-debug (quote ("all" (t nil nil))))
 ;;'(jde-compile-option-optimize t)
)
