thirdpartylibs:
	tar cfvz /tmp/modnlp-3rdparty.tgz MinML2.jar \
	antlr-2.7.6.jar \
	capte.jar \
	colt.jar \
	commons-codec-1.2.jar \
	commons-collections.jar \
	commons-io-2.0.1.jar \
	commons-logging-1.1.1.jar \
	commons-pool-1.2.jar \
	exist-modules.jar \
	exist.jar \
	gnu-regexp-COPYING \
	gnu-regexp.jar \
	httpclient-3.0.1.jar \
	je.jar \
	jgroups-all.jar \
	jung.jar \
	log4j-1.2.14.jar \
	lucene-analyzers-3.6.0.jar \
	lucene-core-3.6.0.jar \
	lucene-kuromoji-3.6.0.jar \
	prefuse.jar \
	resolver.jar \
	sunxacml.jar \
	xmldb.jar \
	xmlrpc-1.2-patched.jar

teclibs:
	tar cfvz /tmp/modnlp-teclibs.tgg idx.jar \
	modnlp.jar \
	teccli.jar \
	tecser.jar \
